### ISSUE TITLE
after adding -t, pipeline initiation fails with

### ISSUE THREAD

**Issue by devcurmudgeon** [perryl/concourse-scripts#16]
failed to evaluate variables into template: 92 error(s) occurred:
- unbound variable in template: 'ybd-cache-password'
- unbound variable in template: 'ybd-cache-server'
- unbound variable in template: 'ybd-cache-password'
- unbound variable in template: 'ybd-cache-server'
- unbound variable in template: 'ybd-cache-password'
- etc...

**Comment by perryl** [comment]
This issue should be solved as of https://github.com/perryl/concourse-scripts/commit/2c26e1f4941a8e95efafe79b0c8e7c61f55b2912
