### ISSUE TITLE
Add single stratum parsing

### ISSUE THREAD

**Issue by perryl** [perryl/concourse-scripts#8]
This was removed as part of large scale changes to `parser.py`; this should be re-added now, preferably with its own argument, e.g. `--strata=/path/to/definitions/strata/stratum.morph`

**Comment by perryl** [comment]
Re-added as of https://github.com/perryl/concourse-scripts/commit/e44e49fb6c8a8580cd9c574f53ba92500cecd6f1

**Comment by mwilliams-ct** [comment]
As of 1c11317 fails again due to lack of architecture

**Comment by perryl** [comment]
Fixed as of https://github.com/perryl/concourse-scripts/commit/381ec8101f683ff157d42e8326bbc83f6e164389
