### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'definitions/strata/graphics-common.morph'

### ISSUE THREAD

**Issue by devcurmudgeon** [perryl/concourse-scripts#9]
~/Projects/2016/concourse-scripts>./construct-pipelines.sh ~/Projects/2016/definitions/systems/genivi-demo-platform-x86_64-generic.morph
Traceback (most recent call last):
  File "./parser.py", line 119, in <module>
    SystemsParser().main()
  File "./parser.py", line 102, in main
    strata_yamls = [self.open_file(x) for x in strata_paths]
  File "./parser.py", line 49, in open_file
    with open(morphology, 'r') as f:
IOError: [Errno 2] No such file or directory: 'definitions/strata/graphics-common.morph'

**Comment by perryl** [comment]
I believe this is due to the path to definitions being hardcoded in parser.py, rather than using the full path given by the argument. Thanks for bringing this to my attention! I'm working on a fix for this now.

**Comment by perryl** [comment]
Fixed as of https://github.com/perryl/concourse-scripts/commit/298f45e749ce825c10914a1b7171e746d3251ef3
